export const allProducts = [
  {
    id: 1,
    name: "Organic Tomatoes",
    price: 4.99,
    category: "vegetables",
    rating: 4.8,
    image: "https://i.ibb.co.com/21QtLNfS/totatos.jpg",
    description: "Fresh, juicy organic tomatoes grown without pesticides",
    nutrition: "Vitamin C, Lycopene, Potassium",
    origin: "Local Farm",
    inStock: true,
  },
  {
    id: 2,
    name: "Fresh Spinach",
    price: 3.49,
    category: "vegetables",
    rating: 4.9,
    image: "https://i.ibb.co.com/LzhfmxTt/Fresh-Spinach.jpg",
    description:
      "Nutrient-rich green leafy spinach, perfect for salads and smoothies",
    nutrition: "Iron, Vitamin K, Calcium",
    origin: "Organic Farm",
    inStock: true,
  },
  {
    id: 3,
    name: "Crispy Carrots",
    price: 2.99,
    category: "vegetables",
    rating: 4.7,
    image: "https://i.ibb.co.com/GfZLBd5v/carrots.jpg",
    description: "Sweet and crunchy carrots, ideal for snacking and cooking",
    nutrition: "Beta-Carotene, Fiber, Vitamin A",
    origin: "Local Farm",
    inStock: true,
  },
  {
    id: 4,
    name: "Bell Peppers",
    price: 3.99,
    category: "vegetables",
    rating: 4.6,
    image: "https://i.ibb.co.com/wrFxn3YV/bell.jpg",
    description: "Colorful bell peppers packed with vitamins and antioxidants",
    nutrition: "Vitamin C, Vitamin A, Antioxidants",
    origin: "Green Valley Farm",
    inStock: true,
  },
  {
    id: 5,
    name: "Ripe Bananas",
    price: 1.99,
    category: "fruits",
    rating: 4.8,
    image: "https://i.ibb.co.com/h1WfvZ41/bananas.jpg",
    description:
      "Perfectly ripe bananas full of natural sweetness and potassium",
    nutrition: "Potassium, Vitamin B6, Vitamin C",
    origin: "Tropical Groves",
    inStock: true,
  },
  {
    id: 6,
    name: "Fresh Apples",
    price: 5.99,
    category: "fruits",
    rating: 4.9,
    image: "https://i.ibb.co.com/rf69pp4S/apple.jpg",
    description:
      "Crisp, sweet apples with natural flavor, perfect for eating fresh",
    nutrition: "Fiber, Vitamin C, Polyphenols",
    origin: "Orchard Fresh",
    inStock: true,
  },
  {
    id: 7,
    name: "Orange Oranges",
    price: 4.49,
    category: "fruits",
    rating: 4.7,
    image: "https://i.ibb.co.com/h1y8Ng3J/orange.jpg",
    description: "Juicy citrus oranges loaded with natural vitamin C",
    nutrition: "Vitamin C, Folate, Flavonoids",
    origin: "Citrus Grove",
    inStock: true,
  },
  {
    id: 8,
    name: "Strawberries",
    price: 6.99,
    category: "fruits",
    rating: 4.9,
    image: "https://i.ibb.co.com/WvGG9DnG/straw.jpg",
    description: "Delicious, sweet strawberries fresh from the farm",
    nutrition: "Vitamin C, Antioxidants, Manganese",
    origin: "Berry Farm",
    inStock: true,
  },
  {
    id: 9,
    name: "Milk",
    price: 3.99,
    category: "dairy",
    rating: 4.8,
    image: "https://i.ibb.co.com/YBscFP1m/milk.jpg",
    description: "Pure, fresh milk from grass-fed cows",
    nutrition: "Calcium, Protein, Vitamin D",
    origin: "Dairy Farm",
    inStock: true,
  },
  {
    id: 10,
    name: "Cheese",
    price: 7.99,
    category: "dairy",
    rating: 4.7,
    image: "https://i.ibb.co.com/nq88KSvd/cheese.jpg",
    description: "Creamy artisan cheese with rich flavor",
    nutrition: "Calcium, Protein, Fat-soluble Vitamins",
    origin: "Artisan Dairy",
    inStock: true,
  },
  {
    id: 11,
    name: "Yogurt",
    price: 4.99,
    category: "dairy",
    rating: 4.8,
    image: "https://i.ibb.co.com/Qy0xnpV/yogurt.jpg",
    description: "Smooth, creamy yogurt with live probiotic cultures",
    nutrition: "Probiotics, Calcium, Protein",
    origin: "Probiotic Dairy",
    inStock: true,
  },
  {
    id: 12,
    name: "Brown Rice",
    price: 6.99,
    category: "grains",
    rating: 4.7,
    image: "https://i.ibb.co.com/w34mpMG/rice.jpg",
    description: "Wholesome brown rice, perfect for healthy meals",
    nutrition: "Fiber, Manganese, Magnesium",
    origin: "Grain Fields",
    inStock: true,
  },
  {
    id: 13,
    name: "Fish",
    price: 8.99,
    category: "fish",
    rating: 4.7,
    image: "https://i.ibb.co.com/QvvpRm2q/fish.jpg",
    description: "Fresh fish rich in protein and omega-3 fatty acids",
    nutrition: "Protein, Omega-3, Vitamin D",
    origin: "Water",
    inStock: true,
  },
];
